.PHONY: all sandbox hasnah

all: 2020  

2017: 
	g++ -std=c++11 -stdlib=libc++ 2020.cpp -o 2020 && ./2020

2020: 
	g++ -std=c++11 -stdlib=libc++ 2017.cpp -o 2017 && ./2017

sandbox:
	g++ -std=c++11 -stdlib=libc++ sandbox.cpp -o sandbox && ./sandbox


