.PHONY: all sand box mayan_greg

all: sandbox mayan_greg

sandbox: 
	g++ -std=c++11 -stdlib=libc++ .cpp -o sandbox && ./sandbox
	
mayan_greg:
	g++ -std=c++11 -stdlib=libc++ mayan_greg.cpp -o mayan_greg && ./mayan_greg